### PR TITLE
Update usage of coastlines to work only using the Mapping Toolbox

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
Upon MATLAB **R2020b** the names for the coastlines of the Mapping Toolbox are different to previous releases:
**R2020a and lower**
```matlab
load('coast')  % output with "long" and "lat"
```
**R2020b and higher**
```matlab
load('coastlines')  % output with "coastlon" and "coastlat"
```
Until now this was probably not recognized as a problem, as there was still a file `coast.mat` available via another toolbox:
```
>> which coast.mat -all
C:\Program Files\MATLAB\R2022a\examples\bioinfo\data\coast.mat
>> which coastlines.mat -all
C:\Program Files\MATLAB\R2022a\toolbox\map\mapdata\coastlines.mat
```
Working with the pre-release of **R2023a** it seems that this file is now removed from the Bioinformatic Toolbox:
```
>> which coast.mat -all
'coast.mat' not found.
>> which coastlines.mat -all
C:\Program Files\MATLAB\R2023a\toolbox\map\mapdata\coastlines.mat
````

This PR updates StackSplit 3.0 to run with MATLAB R2023a, while keep working with lower MATLAB versions. Therefore, the function `SS_check_matlab_version.m` is expanded. Queries are added in `SS_gen_worldmap.m` and the queries in `SS_disp_Esurf_single.m` and `SS_stack_Esurf.m` are adjusted. I set R2020a/R2020b as the limit (not R2022b/R2023a) to make no usage of the Bioinformatic Toolbox anymore for versions between R2020b and R2022b.

-------------------
**Testing**
- **2023/01/04**: Please note, until now this was only tested with R2022a and the pre-release for R2023a.
- **2023/01/09**:

|MATLAB|Windows|Linux|
|---|---|---|
|R2018a|no license|:white_check_mark:|
|R2022a|not tested|:white_check_mark:|
|R2022b|:white_check_mark:|not tested|
|R2023a (pre-release)|:white_check_mark:|no license|

### CODE REVIEW

**Comment by michaelgrund** [comment]
We can make a minor v3.1 release in the near future to include the changes made in the last >12 months.

**Comment by yvonnefroehlich** [comment]
> We can make a minor v3.1 release [...]

That's fine with me.

> [...] in the near future [...]

Meaning within the time period January to Feburary?

> [...] to include the changes made in the last >12 months.

Do you expect me to make any specific changes for this release?
Maybe I can test StackSplit a bit more with the pre-release of R2023a.

**Comment by michaelgrund** [comment]
> Meaning within the time period January to Feburary?

January 2022 till now (last commit before new release).

> Do you expect me do any specific changes for this release? Maybe I can test StackSplit a bit more with the prerelease of R2023a.

If you have time that would be great since I don't have the new 2023 version. I think the SplitLab versions, no matter which, will potentially cause errors in the future when new MATLAB versions are released.

**Comment by yvonnefroehlich** [comment]
> > > [...] in the near future [...]
>
> > Meaning within the time period January to Feburary?
> 
> January 2022 till now (last commit before new release).
> 
Yep, sure. But what do you mean with "near future"? Meaning until when do I have to finish my PRs - this week[end], this month, or within Feburary 🙂?
>
> > Do you expect me do any specific changes for this release? Maybe I can test StackSplit a bit more with the prerelease of R2023a.
> 
> If you have time that would be great since I don't have the new 2023 version. I think the SplitLab versions, no matter which, will potentially cause errors in the future when new MATLAB versions are released.
>
I started going through the single StackSplit functions in PR #11. Currently, I feel I don't have the time to also look at the SplitLab functions and to include changes for higher MATLAB versions with backwards compatibility, which are introduced during the installation process of StackSplit. _So far_, no changes on _my personal_ SplitLab version where necessary when changing from R2022a/b to R2023a. However, I made several changes when changing from R2018a/b to R2020a/b and a few when changing from R2020a/b to R2022a/b.

**Comment by yvonnefroehlich** [comment]
In principle this PR should be finished. @michaelgrund can you please review it. Thanks!

**Review by michaelgrund — APPROVED** [review]

**Comment by yvonnefroehlich** [comment]
> We can make a minor v3.1 release in the near future to include the changes made in the last >12 months.

@michaelgrund do you plan to release v3.1 (or v4.0) before or after Christmas, or move it to 2024?

**Pull request merged**
