### PR TITLE
Replace removed function "resizem" by "imresize" (up on R2023b) 

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
This PR aims to replace `resizem` by  `imresize`, which is removed in MATLAB R2023b:

- [x] Expand query in `SS_check_matlab_version` for R2023b
- [x] Update checks in `SS_disp_Esurf_single` , `SS_stack_Esurf`,  `SS_gen_worldmap` 
- [x] Add check in `SS_check_input.m`
- [x] Use always `matlab_version` as variable name for output of `SS_check_matlab_version`
- [x] Check spelling: query / queries NOT quarry or quarries
- [x] It's MATLAB: start at `1`, close loops with `end`, commt using `%`

See also:
- PR #14
- PR #12
- PR #11
- PR #10 
- PR #9

**Testing**
|MATLAB|Windows|Linux|
|---|---|---|
|R2018a|no license|TODO|
|R2022a|not tested|TODO|
|R2022b|TODO|not tested|
|R2023a (pre-release) | skiped | no license |
|R2023a | skiped | no license so far |
|R2023b (pre-release) | end of June - mide of August | no license |

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
_Slightly modified from the orignal post at https://github.com/michaelgrund/stacksplit/pull/12#issuecomment-1396900646 by @yvonnefroehlich_:

As `resizem` will be removed in a further release, we have to replace it correctly in `SS_check_input.m`:
- [`resizem`](https://de.mathworks.com/help/map/ref/resizem.html) - (To be removed) Resize regular data grid
- [`georesize`](https://de.mathworks.com/help/map/ref/georesize.html) - Resize geographic raster
- [`imresize`](https://de.mathworks.com/help/matlab/ref/imresize.html) - Resize image

From my understanding `georesize` does not fit our purpose and needs. Thus, I replaced `resizem` (which uses by default nearest neighbor interpolation) by `imresize` with the interpolation method set to `"nearest"` (see commit https://github.com/michaelgrund/stacksplit/pull/13/commits/dcb17db86491bc8957a08c088303a7905125b654).
This leads to the same results in most of the cases. But in some cases, I recognized unexpected differences between the matrix resized via `resizem` and the matrix resized via `imresize`.

_MATLAB script_:
<details><summary>Click to expand MATLAB script</summary>
<p>

```matlab
% resizem - (To be removed) Resize regular data grid
% georesize - Resize geographic raster
% imresize - Resize image

% resizem(Esurfold,[check_acc size_dt_test])

% interpolation methods
interpol_meth_all = ["nearest", "bilinear", "bicubic"];

% factor for scaling the values of the elements of matries 
% 1, 10, 100
value_range = 10;

% increase matrix_02 relative to matrix_01
add_size = 3;

for i_meth = 1:1:length(interpol_meth_all)

    for red_size = 2:1:30
       
        matrix_01 = (rand(red_size)-0.5) * value_range;
        matrix_02 = (rand(red_size+add_size)-0.5) * value_range;
        
        matrix_01_resizem = resizem(matrix_01, [red_size, red_size]);
        matrix_02_resizem = resizem(matrix_02, [red_size, red_size]);
        
        matrix_01_imresize = imresize(matrix_01, [red_size, red_size]);
        matrix_02_imresize = imresize(matrix_02, [red_size, red_size], ...
            interpol_meth_all(i_meth));
        
        diff_01 = matrix_01 - matrix_01_resizem;
        diff_01_im = matrix_01_resizem - matrix_01_imresize;
        diff_02_im = matrix_02_resizem - matrix_02_imresize;
        
        c_abs_max = 1 * value_range/2;
        
        tl = tiledlayout(4,2, 'TileSpacing','Compact'); % rows, columns
        tl.TileSpacing = 'compact';
        tl.Padding = 'compact';
        title(tl,"resizem vs. imresize | interpol.: " + interpol_meth_all(i_meth) + ...
              " | matrix resized to: " + string(red_size) + "x" + string(red_size))
    
        nexttile
        p01 = image(matrix_01, 'CDataMapping','scaled');
        title("matrix-01-orignal-" + string(red_size) + "x" + string(red_size))
        axis equal
        axis off
        colorbar()
        clim([-c_abs_max,c_abs_max])
        
        nexttile
        p02 = image(matrix_02, 'CDataMapping','scaled');
        title("matrix-02-orignal-" + string(red_size+add_size) + "x" + string(red_size+add_size))
        axis equal
        axis off
        colorbar()
        clim([-c_abs_max,c_abs_max])
        
        nexttile
        p01_re = image(matrix_01_resizem, 'CDataMapping','scaled');
        title("matrix-01-resizem")
        axis equal
        axis off
        colorbar()
        clim([-c_abs_max,c_abs_max])
        
        nexttile
        p02_re = image(matrix_02_resizem, 'CDataMapping','scaled');
        title("matrix-02-resizem")
        axis equal
        axis off
        colorbar()
        clim([-c_abs_max,c_abs_max])
        
        nexttile
        p01_im = image(matrix_01_imresize, 'CDataMapping','scaled');
        title("matrix-01-imresize")
        axis equal
        axis off
        colorbar()
        clim([-c_abs_max,c_abs_max])
        
        nexttile
        p02_im = image(matrix_02_imresize, 'CDataMapping','scaled');
        title("matrix-02-imresize")
        axis equal
        axis off
        colorbar()
        clim([-c_abs_max,c_abs_max])
        
        nexttile
        p01_diff = image(diff_01_im, 'CDataMapping','scaled');
        title("matrix-01-resizem-imresize")
        axis equal
        axis off
        colorbar()
        clim([-c_abs_max,c_abs_max])
        
        nexttile
        p02_diff = image(diff_02_im, 'CDataMapping','scaled');
        title("matrix-02-resizem-imresize")
        axis equal
        axis off
        colorbar()
        clim([-c_abs_max,c_abs_max])

        % requires Scientific colormaps by F. Crameri available on your system
        % colormap(crameri('vik'))

        % Please be aware, that by uncommenting the following lines, running 
        % this script will save or write several PNG files to your current
        % working dictionary. The amount of files is related to the values
        % set at the begins of the loops.
        % saveas(gcf,"test_resizem_vs_imresize_" + interpol_meth_all(i_meth) + ...
        %   "_" + string(red_size) + ".png")
    
    end % red_size 

end % i_meth 
```
</p>
</details>

_Output figures_:
Externally combined to one PDF file.\
Exemplarly produced for `value_range=10` and `add_size=3`.\
For details please see the MATLAB script above. 

- Used for the changes in `SS_check_input.m`: Figures for imresize with [`"nearest"`](https://github.com/michaelgrund/stacksplit/files/10456486/test_resizem_vs_imresize_nearest_ALL.pdf)
- For sake of completenesse: Figures for `imresize` with [`"bilinear"`](https://github.com/michaelgrund/stacksplit/files/10456487/test_resizem_vs_imresize_bilinear_ALL.pdf) and [`"bicubic"`](https://github.com/michaelgrund/stacksplit/files/10456489/test_resizem_vs_imresize_bicubic_ALL.pdf)

**Comment by yvonnefroehlich** [comment]
@michaelgrund it seems like you want to make the v3.1 release (I saw you set up a 3.1 milestone)? 

At the moment, I can unfortunately not provide a solution for the issue raised in this PR. I even can not state which is the "correct" interpolation result, the one by `resizem` (main branch) or the one by `imresize` (this branch / PR).
There are different options:
- Keep `resizem` for now
- Trust MATLAB (and me) and change to `imresize`

Currently, I can not guarantee any availability for April. For the rest of March, my time is a bit limited due to work load.

**Comment by michaelgrund** [comment]
> @michaelgrund it seems like you want to make the v3.1 release (I saw you set up a 3.1 milestone)?
> 
> At the moment, I can unfortunately not provide a solution for the issue raised in this PR. I even can not state which is the "correct" interpolation result, the one by `resizem` (main branch) or the one by `georesize` (this branch / PR). There are different options:
> 
>     * Keep `resizem` for now
> 
>     * Trust MATLAB (and me) and change to `georesize`
> 
> 
> Currently, I can not guarantee any availability for April. For the rest of March, my time is a bit limited due to work load.

Well there's no hurry to release the new version, just set up a milestone without a due date. At the moment I would say we should keep `resizem`.

**Comment by yvonnefroehlich** [comment]
> Well there's no hurry to release the new version, just set up a milestone without a due date. At the moment I would say we should keep `resizem`.

OK. Sounds good. Hm. So, we go with leaving this PR open and hoping I figure it out when I have time again?

**Comment by yvonnefroehlich** [comment]
I analyzed the cases which show differences between using `resizem` or `imresize` in more detail.
Even MATLAB proposes that users should or can replace `resizem` by `imresize` 
(please see https://de.mathworks.com/help/map/ref/resizem.html#mw_9c2f5e05-9c4d-4343-b1ea-5310be2fbb57), I feel the (nearest neighbor) interpolation approaches/procedures are not completely identical. Thus, it seems that it is not directly possible to replace `resizem` by `imresize` with always identical results.

run04_mixed_Fig01

run04_mixed_Fig02

run04_mixed_Fig04

PDF file with all figures: [test_resizem_vs_imresize_ALL.pdf](https://github.com/michaelgrund/stacksplit/files/11979172/test_resizem_vs_imresize_ALL.pdf)

<details><summary>Click for MATLAB code</summary>
<p>

```matlab

% Random test matrix
matrix_01 = [
    5 9 6 2 4 5;
    -1 6 4 3 -5 5;
    8 -3 9 1 -2 3;
    6 -7 2 -4 7 1;
    8 -6 1 2 3 -9;
    -4 7 2 -6 9 -7;
];

c_abs_max = 10;
i_red_max = 20;


% Run 1: red_size, red_size -> "equal"
% Run 2: red_size, red_size+1 -> "plusone"

for i_red = 1:1:i_red_max

    red_size = i_red;

    % Run 1
    matrix_01_resizem = resizem(matrix_01, [red_size, red_size]);
    matrix_01_imresize = imresize(matrix_01, [red_size, red_size], "nearest");

    % Run 2
    % matrix_01_resizem = resizem(matrix_01, [red_size, red_size+1]);
    % matrix_01_imresize = imresize(matrix_01, [red_size, red_size+1], "nearest");
      
    figure()
    
    tl = tiledlayout(1,4, 'TileSpacing','Compact'); % rows, columns
    tl.TileSpacing = 'compact';
    tl.Padding = 'compact';
    title(tl, "6x6 \rightarrow " + num2str(red_size) + "x" + num2str(red_size))

    nexttile
    p_org = image(matrix_01, 'CDataMapping','scaled');
    title("original matrix")
    axis equal
    axis off
    clim([-c_abs_max,c_abs_max])

    nexttile
    p_resize = image(matrix_01_resizem, 'CDataMapping','scaled');
    title("resizem")
    axis equal
    axis off
    clim([-c_abs_max,c_abs_max])
    
    nexttile
    p_imresize = image(matrix_01_imresize, 'CDataMapping','scaled');
    title("imresize")
    axis equal
    axis off
    clim([-c_abs_max,c_abs_max])
    
    nexttile
    p_diff = image(matrix_01_imresize-matrix_01_resizem, 'CDataMapping','scaled');
    title("imresize-resizem")
    axis equal
    axis off
    clim([-c_abs_max,c_abs_max])

    % Requires Scientific colour maps by Fabio Crameri
    colormap(crameri('vik', c_abs_max*2))
    colorbar()

    % Saves plots to your current working dictionary

    % Run 1
    % saveas(gcf,"test_resizem_vs_imresize_" + num2str(i_red) + "equal.png")
    
    % Run 2
    % saveas(gcf,"test_resizem_vs_imresize_" + num2str(i_red) + "plusone.png")

end  % i_red 
```

</p>
</details>

**Comment by michaelgrund** [comment]
I see that the results are not fully identical. In contrast, is there any other solution for this issue?

**Comment by yvonnefroehlich** [comment]
> I see that the results are not fully identical. In contrast, is there any other solution for this issue?

MATLAB suggests replacing `resizem` by `georesize` or `imresize`. The results are mostly identically. The difference for some cases seem to be caused by a slightly other interpolation approach. Thus, I feel I replaced it as proposed by MATLAB. One idea was to report this issue along with the survey for the pre-release of R2023b. It's out since end of June, but it is almost impossible for me to do this in July. Maybe (hopefully) I can do this in August. So, I have no other solution for this issue at the moment 🙁. However, so far MATLAB does not state the release, in which they will remove `resizem`.

**Comment by yvonnefroehlich** [comment]
> One idea was to report this issue along with the survey for the pre-release of R2023b. It's out since end of June, but it is almost impossible for me to do this in July. Maybe (hopefully) I can do this in August. 

I made this survey this afternoon (2023/08/09) and reported the/my resizem-to-imresize issue. In case I get any feedback from MATLAB regarding this issue, I will report it in this PR. I feel this all I can do for now.

**Comment by yvonnefroehlich** [comment]
> However, so far MATLAB does not state the release, in which they will remove `resizem`.

`resizem` has been removed up on the (pre)release of R2023b.

**Comment by yvonnefroehlich** [comment]
MATLAB confirmed that there are differences between the results of `resizem` and `imresize` for some cases. As `resizem` is not  available up on R2023b, we have to replace it by `imresize` even though the results are not always identical, in case we want StackSplit to run under MATLAB versions higher or equal R2023b.

**Comment by michaelgrund** [comment]
> MATLAB confirmed that there are differences between the results of `resizem` and `imresize` for some cases. As `resizem` is not available up on R2023b, we have to replace it by `imresize` even though the results are not always identical, in case we want StackSplit to run under MATLAB versions higher or equal R2023b.

Then I would suggest to go with `imresize` for MATLAB versions >= 2023b and allow to use `resizem` if older versions are still installed. For the latter one we could add another query in https://github.com/michaelgrund/stacksplit/blob/e8124667294e49eff4f73e5b912ec2a182d0c84d/StackSplit/SS_check_matlab_version.m#L66

**Comment by yvonnefroehlich** [comment]
> > MATLAB confirmed that there are differences between the results of `resizem` and `imresize` for some cases. As `resizem` is not available up on R2023b, we have to replace it by `imresize` even though the results are not always identical, in case we want StackSplit to run under MATLAB versions higher or equal R2023b.
> 
> Then I would suggest to go with `imresize` for MATLAB versions >= 2023b and allow to use `resizem` if older versions are still installed. For the latter one we could add another query in
> 
> https://github.com/michaelgrund/stacksplit/blob/e8124667294e49eff4f73e5b912ec2a182d0c84d/StackSplit/SS_check_matlab_version.m#L66

I started working on this, but I have to cross check later (Edit: probably / hopefully on the weekend), whether all queries work correctly.

**Comment by yvonnefroehlich** [comment]
> > > MATLAB confirmed that there are differences between the results of `resizem` and `imresize` for some cases. As `resizem` is not available up on R2023b, we have to replace it by `imresize` even though the results are not always identical, in case we want StackSplit to run under MATLAB versions higher or equal R2023b.
> > 
> > 
> > Then I would suggest to go with `imresize` for MATLAB versions >= 2023b and allow to use `resizem` if older versions are still installed. For the latter one we could add another query in
> > https://github.com/michaelgrund/stacksplit/blob/e8124667294e49eff4f73e5b912ec2a182d0c84d/StackSplit/SS_check_matlab_version.m#L66
> 
> I started working on this, but I have to cross check later (Edit: probably / hopefully on the weekend), whether all queries work correctly.

@michaelgrund can you please take a look at this PR and report whether expanding the queries in the current way makes sense to you? Thanks! I also added some explanation regarding these queries. Feel free to suggest improvements to the formulations.

**Comment by yvonnefroehlich** [comment]
MATLAB R2023b has been released. I do not expect any changes / problems compared to the pre-release, but I will check this in the next few weeks. **_Edit_** (2023/10/12): Very likely not before November, and definitely not during the third week of November.

**Comment by michaelgrund** [comment]
> MATLAB R2023b has been released. I do not expect any changes / problems compared to the pre-release, but I will check this in the next few weeks. **_Edit_** (2023/10/12): Very likely not before November, and definitely not during the third week of November.

Feel free to check when ever you have time. So far everything looks fine to me.

**Comment by yvonnefroehlich** [comment]
So, the only new thing I am facing with R2023 so far is this warning:
```
Warning: In a future release, UI components will not be
included in the output. To include UI components, use
the exportapp function. 
> In print (line 86)
In saveresult (line 114)
In postcardware (line 31)
In splitlab (line 197) 
```
But this is an issue with SplitLab. Thus it is unrelated to this PR and we have to look and handle this separately.

**Comment by yvonnefroehlich** [comment]
@michaelgrund, are there, besides the currently opened PRs and the release-related PRs (updating the changelog, README, etc.) changes you want me to do for release v3.1 🙂?

**Comment by michaelgrund** [comment]
> @michaelgrund, are there, besides the currently opened PRs and the release-related PRs (updating the changelog, README, etc.) changes you want me to do for release v3.1 🙂?

I don't think so. Thanks so far.

**Review by michaelgrund — APPROVED** [review]

**Comment by yvonnefroehlich** [comment]
> > @michaelgrund, are there, besides the currently opened PRs and the release-related PRs (updating the changelog, README, etc.) changes you want me to do for release v3.1 🙂?
> 
> I don't think so. Thanks so far.

Great! Happy to help 🙂, as long I have a MATLAB license.

**Pull request merged**
