### PR TITLE
Improve loading of matTaup Java class

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
Loading the matTaup Java class appears challenging. This PR aims to ease this by making further changes to the original SplitLab version (SL 1.0.5 and SL 1.2.1) and adding a new function to SplitLab. The code is oriented on the function of SplitLab version 1.9.0 (https://github.com/IPGP/splitlab/blob/master/SplitLab1.9.0/Tools/checkmattaupclass.m), which is currently not finished, and there seems to be no activity in pushing this forward.

- Introduce new function `checkmattaupclass.m` or `checkmattaupclass_SS.m`
- Make further modifications of `splitlab.m` or `splitlab_SS.m`
-  Adjust `install_StackSplit.m` and `uninstall_StackSplit.m`

**Testing**
- Windows: R2024a |  until now no issues
- Linux: R2023a | until now no issues

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
@michaelgrund, before putting more work into this PR, I would appreciate getting feedback on whether you think the suggested change is an improvement to StackSplit and this PR is considered to be merged after an appropriate review 🙂 .

**Comment by michaelgrund** [comment]
> @michaelgrund, before putting more work into this PR, I would appreciate getting feedback on whether you think the suggested change is an improvement to StackSplit and this PR is considered to be merged after an appropriate review 🙂 .

In principle I'm fine with the updates. Is it possible to benchmark the old implementation against the new one to see if the results differ?

**Comment by yvonnefroehlich** [comment]
> > @michaelgrund, before putting more work into this PR, I would appreciate getting feedback on whether you think the suggested change is an improvement to StackSplit and this PR is considered to be merged after an appropriate review 🙂 .
> 
> In principle I'm fine with the updates. Is it possible to benchmark the old implementation against the new one to see if the results differ?

Hm. I am currently not sure what you mean with 
- "old and new implementations"
   - Without vs. with the changes in this PR?
   - The versions of `checkmattaupclass.m` in SplitLab 1.9.0 vs. the one in this PR?
- "results"
  - The loading time when starting SplitLab? There should be no impact on starting StackSplit. 
  - The calculated travel times and paths based on the chosen 1-D Earth model? The TauP calculation functions are untouched in this PR, so there should be no differences in the travel times and paths.
  - The single and multi-event shear-wave splitting measurements? There should be no differences, as TauP is only used to calculate the theoretical travel times to facilitate finding the desired phases in the seismograms and to make plots showing travel times and phases.

**Comment by michaelgrund** [comment]
> > > @michaelgrund, before putting more work into this PR, I would appreciate getting feedback on whether you think the suggested change is an improvement to StackSplit and this PR is considered to be merged after an appropriate review 🙂 .
> > 
> > 
> > In principle I'm fine with the updates. Is it possible to benchmark the old implementation against the new one to see if the results differ?
> 
> Hm. I am currently not sure what you mean with
> 
>     * "old and new implementations"
>       
>       * Without vs. with the changes in this PR?
>       * The versions of `checkmattaupclass.m` in SplitLab 1.9.0 vs. the one in this PR?
> 
>     * "results"
>       
>       * The loading time when starting SplitLab? There should be no impact on starting StackSplit.
>       * The calculated travel times and paths based on the chosen 1-D Earth model? The TauP calculation functions are untouched in this PR, so there should be no differences in the travel times and paths.
>       * The single and multi-event shear-wave splitting measurements? There should be no differences, as TauP is only used to calculate the theoretical travel times to facilitate finding the desired phases in the seismograms and to make plots showing travel times and phases.

Ok, if there's no impact on the calculated travel times etc. than I'm fine with the changes 😉

**Comment by yvonnefroehlich** [comment]
> > > > @michaelgrund, before putting more work into this PR, I would appreciate getting feedback on whether you think the suggested change is an improvement to StackSplit and this PR is considered to be merged after an appropriate review 🙂 .
> > > 
> > > 
> > > In principle I'm fine with the updates. Is it possible to benchmark the old implementation against the new one to see if the results differ?
> > 
> > 
> > Hm. I am currently not sure what you mean with
> > ```
> > * "old and new implementations"
> >   
> >   * Without vs. with the changes in this PR?
> >   * The versions of `checkmattaupclass.m` in SplitLab 1.9.0 vs. the one in this PR?
> > 
> > * "results"
> >   
> >   * The loading time when starting SplitLab? There should be no impact on starting StackSplit.
> >   * The calculated travel times and paths based on the chosen 1-D Earth model? The TauP calculation functions are untouched in this PR, so there should be no differences in the travel times and paths.
> >   * The single and multi-event shear-wave splitting measurements? There should be no differences, as TauP is only used to calculate the theoretical travel times to facilitate finding the desired phases in the seismograms and to make plots showing travel times and phases.
> > ```
> 
> Ok, if there's no impact on the calculated travel times etc. than I'm fine with the changes 😉

The calculations of the travel times and paths is not modified in this PR. These are handled by MatTaup written by Qin Li (based on the Java TauP Toolkit by Crotwell 1999), not by SplitLab. Only the loading of the provided Java classes is changed in this PR.

I just made a small test comparing the results obtained with SplitLab and [ObsPy](https://docs.obspy.org/packages/obspy.taup.html) which also uses the Java TauP Toolkit by [[Crotwell1999]](https://docs.obspy.org/citations.html#crotwell1999).

**Earthquake data**: Earth model iasp91 | hypocentral depth 0 km | epicentral distance 130°

**SplitLab**
| travel paths | travel times | travel curves |
| --- | --- | --- |
| SL_taup_path |  Phase: PKS         Time:    1354.753(s) <br/> Phase: PKS         Time: 1354.699(s) <br/> Phase: PKKS        Time: 1934.717(s) <br/>  Phase: SKS         Time: 1581.361(s) <br/>  Phase: SKKS        Time: 1700.372(s) <br/>  Phase: SKKS        Time: 2162.666(s) | SL_taup_time |

**ObsPy**
| travel paths and travel times | |
| --- | --- |
| map_travelpath_130deg_PKS_PKS_SKS_SKKS_PKKS_SKKS |...........................................................................................................|

-----------------
_Please note_:

* The SplitLab scripts for plotting the time curves and travel paths have to be updated by the users if higher MATLAB versions should be used. Furthermore, users have to be careful with the color-coding, as the colors are set in both scripts as cell arrays (not using, e.g., `containers.Map`) independently (no separate function). This is especially relevant if there are two travel paths possible for one phase.
https://github.com/IPGP/splitlab/blob/8df1ed5a8aa8aeef3556b8ade4aa3d1b56cb8399/SplitLab1.9.0/matTaup/taupCurve.m#L76
https://github.com/IPGP/splitlab/blob/8df1ed5a8aa8aeef3556b8ade4aa3d1b56cb8399/SplitLab1.9.0/matTaup/taupPath.m#L148
* The PKKS phase is not directly used by SplitLab, but can be included by adjusting the script `configpanelPHASES.m`
* The plot for the ObsPy result is generated with https://github.com/yvonnefroehlich/gmt-pygmt-plotting/blob/main/003_taup/01_travel_path/taup_path.py.

**Comment by yvonnefroehlich** [comment]
So @michaelgrund, I think this PR should be ready for a first round of review.

I added a comment in the scripts that the change is only about loading the related java classes not about the calculation of the travel times and curves itself.

**Review by michaelgrund — APPROVED** [review]

**Pull request merged**
